### ISSUE TITLE
Set python package versions

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus_app#130]
Right now when the container is built the latest version of miniconda is used and in the requirements file for packages like numpy, scipy, scikit-learn there are no specific versions given. At some point we might want to consider setting versions for all packages.

**Comment by billspat** [comment]
additional note, to accommodate scipy versioning in front-end, had to add dependencies in the docker container 40f274a6541d3bc15929550bac311c96734b4176       The front end docker needs scipy since it imports geneplexus.py to be able to do validation, and that module imports scipy.  to keep the front end lean, a solution is to extract the validation code into it's own module which will not require scipy.
